### ISSUE TITLE
define 不能处理 preprocessor directive

### ISSUE THREAD

**Issue by std-microblock** [SnowballXueQiu/sb.h#20]
std::ranges::shuffle(recv);:
链接来个

我想知道他这个incude是怎么做到的

....不是 他真测过这玩意吗

宏只跑一次啊 而且宏本身也不在宏的处理范围内吧

**Comment by Jasonzyt** [comment]
同问 插个眼
我怎么想也想不明白这个是怎么实现的
除非自己写pre-processor

**Comment by std-microblock** [comment]
> 同问 插个眼 我怎么想也想不明白这个是怎么实现的 除非自己写pre-processor

看源码就是写了个define...就是没有实现

**Comment by SnowballXueQiu** [comment]
你说的对 确实没有测试这个玩意（） 刚才看了一下 的确不能替换#include的内容
